### ISSUE TITLE
问题与建议：

### ISSUE THREAD

**Issue by UnCLAS-Prommer** [lc6464/ewtPrograms#2]
加上一个alert，提示视频播放完成。

问题：这个播放会导致不断重播。
想法：是通过计时并与视频时长(.duration)作比较，达到时长时自动停止

测试浏览器：Chrome 92.0

**Comment by lc6464** [comment]
您是否开启了刷视频模式？若开启了，请关闭。
您可以右键刷视频模式的开关以查看刷视频模式的说明。

**Comment by lc6464** [comment]
如果关闭后问题确实不再出现，那我将考虑更改刷视频模式的名称为刷时长模式，您也可以就此提出建议。

**Comment by fengmian309** [comment]
你好，刷视频时长的功能似乎用不了，挂了一会儿之后本周累计看课时长好像还是按照实际观看时间增加而不是乘以16倍速的时间，还是我的理解出错了嘛，谢谢

**Comment by lc6464** [comment]
> 你好，刷视频时长的功能似乎用不了，挂了一会儿之后本周累计看课时长好像还是按照实际观看时间增加而不是乘以16倍速的时间，还是我的理解出错了嘛，谢谢

那个“刷视频模式”开关的用途是是否在播放完成后关闭标签页，如果开启了，就不会关闭标签页，视频会循环播放，如果关闭了，视频播放完后标签页会自动关闭。

现在说说你的情况，假定有一个16分钟的视频，我这个脚本能使它在一分钟内播放完成，假设播放完成后标签页被关闭（无论是自动关的还是手动关的），那这个视频就按照16分钟来计算（实际上你花费了一分钟用于播放）。
如果一个视频反复刷多次，可能会导致后面的无效。
还有就是有一部分数值（比如在线时长等）是依照真实时间的，快速播放脚本无效，你可以使用保持登录脚本使一天都在线。

**Comment by fengmian309** [comment]
> > 你好，刷视频时长的功能似乎用不了，挂了一会儿之后本周累计看课时长好像还是按照实际观看时间增加而不是乘以16倍速的时间，还是我的理解出错了嘛，谢谢
> 
> 那个“刷视频模式”开关的用途是是否在播放完成后关闭标签页，如果开启了，就不会关闭标签页，视频会循环播放，如果关闭了，视频播放完后标签页会自动关闭。
> 
> 现在说说你的情况，假定有一个16分钟的视频，我这个脚本能使它在一分钟内播放完成，假设播放完成后标签页被关闭（无论是自动关的还是手动关的），那这个视频就按照16分钟来计算（实际上你花费了一分钟用于播放）。
> 如果一个视频反复刷多次，可能会导致后面的无效。
> 还有就是有一部分数值（比如在线时长等）是依照真实时间的，快速播放脚本无效，你可以使用保持登录脚本使一天都在线。

好的好的，非常感谢，明白了

**Comment by lc6464** [comment]
> 好的好的，非常感谢，明白了

如果您还有什么疑问欢迎随时提出！

**Comment by fengmian309** [comment]
> > 好的好的，非常感谢，明白了
> 
> 如果您还有什么疑问欢迎随时提出！

感谢大佬

**Comment by lc6464** [comment]
> 感谢大佬

害，算不上大佬啊，要学的还有很多。

**Comment by fengmian309** [comment]
大佬我又来了，播放视频后出现时长上传失败该如何解决
![image](https://user-images.githubusercontent.com/88547870/128595563-465b9e86-72df-49d7-8413-437218044f97.png)

**Comment by lc6464** [comment]
> 大佬我又来了，播放视频后出现时长上传失败该如何解决
> ![image](https://user-images.githubusercontent.com/88547870/128595563-465b9e86-72df-49d7-8413-437218044f97.png)

这个是由于网络问题导致的错误，刷新一下就好了。这个问题通常会出现在好多个标签页一起刷的时候。
如果你只放着一个视频都还经常出现这种情况，那就有必要检查一下你的网络了，偶尔出现的话是正常的。

**Comment by fengmian309** [comment]
> > 大佬我又来了，播放视频后出现时长上传失败该如何解决
> > ![image](https://user-images.githubusercontent.com/88547870/128595563-465b9e86-72df-49d7-8413-437218044f97.png)
> 
> 这个是由于网络问题导致的错误，刷新一下就好了。这个问题通常会出现在好多个标签页一起刷的时候。
> 如果你只放着一个视频都还经常出现这种情况，那就有必要检查一下你的网络了，偶尔出现的话是正常的。

好的谢谢，大佬回的好快

**Comment by lc6464** [comment]
刚好看到邮件通知了。
