### ISSUE TITLE
网页自动关闭的问题

### ISSUE THREAD

**Issue by nmnmcc** [lc6464/ewtPrograms#6]
使用脚本以后，ewt观看视频一段时间后网页会自动关闭，导致无法刷课。
根据个人实验，将网页速度调整为8倍速一下可以大概率避免这种情况的发生。

**Comment by lc6464** [comment]
设计如此，播放完成自动关闭。
开启刷视频模式将不会自动关闭，而是一直循环播放。

**Comment by nmnmcc** [comment]
明白

**Comment by lc6464** [comment]
现在上报速率和视频播放速率无关，就很烦。
之前播放得快，上报得也就快，现在比较短的视频来不及上报就放完了，达不到原来的效果。
